#!/bin/bash

to=${@: -1}              # ultimo argumento: destino
filelist=("${@:1:$#-1}") # todos menos el ultimo

# Si hay menos de dos argumentos, o si hay mas de dos argumentos y el ultimo argumento
# no es un directorio, entonces muestra un mensaje de error
if [[ $# -lt 2 || ($# -gt 2 && ! -d $to) ]]; then
  echo "Usage: mycp file1 file2"
  echo "       mycp file(s) dir"
  exit 1
fi

# ------------------------------------
for from in $filelist; do
  if [ -d "$to" ]; then
    tofile="$to/$(basename $from)"
  else
    tofile="$to"
  fi

  # Agrega el archivo a copylist si el archivo no existe o si el usuario dice que esta bien sobrescribir
  if [ -e "$tofile" ]; then
    echo "$tofile already exists; overwrite (yes/no)? \c"
    read -r answer
    [[ $answer =~ ^(y|yes)$ ]] && copylist="$copylist $from"
  else
    copylist="$copylist $from"
  fi
done

if [ -n "$copylist" ]; then
  cp $copylist $to
fi
# ------------------------------------
# Alternativa:
# cp -i -- "${filelist[@]}" "$to"
